"""Backward-compatible exports for the split discovery SDK implementation."""

from stew._discovery import (
    BalanceType,
    ConflictError,
    CorsConfig,
    DescriptorVersion,
    DiscoveryClient,
    DiscoveryError,
    Endpoint,
    EndpointBinding,
    GatewayClient,
    HealthCheckConfig,
    MiddlewareConfig,
    NotFoundError,
    RegistrationConfig,
    RiskConfig,
    RiskRuleConfig,
    SyncDiscoveryClient,
    TurnstileConfig,
)

__all__ = [
    "DiscoveryClient",
    "SyncDiscoveryClient",
    "GatewayClient",
    "Endpoint",
    "EndpointBinding",
    "BalanceType",
    "HealthCheckConfig",
    "MiddlewareConfig",
    "RegistrationConfig",
    "CorsConfig",
    "RiskRuleConfig",
    "RiskConfig",
    "TurnstileConfig",
    "DescriptorVersion",
    "DiscoveryError",
    "ConflictError",
    "NotFoundError",
]
