"""Backward-compatible exports for the split discovery SDK implementation."""

from stew._discovery import (
    AioGrpcContextPassthroughInterceptor,
    BalanceType,
    build_aio_metadata_client_interceptors,
    ConflictError,
    GrpcContextPassthroughInterceptor,
    collect_grpc_context_metadata,
    CorsConfig,
    DescriptorVersion,
    DiscoveryClient,
    DiscoveryError,
    Endpoint,
    EndpointBinding,
    GatewayClient,
    grpc_context_passthrough,
    grpc_context_passthrough_handler,
    HealthCheckConfig,
    MiddlewareConfig,
    NotFoundError,
    resolve_api_key,
    RegistrationConfig,
    RiskConfig,
    RiskRuleConfig,
    SyncDiscoveryClient,
    TurnstileConfig,
    with_service_auth,
)

__all__ = [
    "DiscoveryClient",
    "SyncDiscoveryClient",
    "GatewayClient",
    "AioGrpcContextPassthroughInterceptor",
    "build_aio_metadata_client_interceptors",
    "GrpcContextPassthroughInterceptor",
    "Endpoint",
    "EndpointBinding",
    "BalanceType",
    "HealthCheckConfig",
    "MiddlewareConfig",
    "RegistrationConfig",
    "collect_grpc_context_metadata",
    "CorsConfig",
    "RiskRuleConfig",
    "RiskConfig",
    "TurnstileConfig",
    "DescriptorVersion",
    "DiscoveryError",
    "ConflictError",
    "grpc_context_passthrough",
    "grpc_context_passthrough_handler",
    "NotFoundError",
    "resolve_api_key",
    "with_service_auth",
]
