# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   apikey_model.py
@Time    :   2026-04-05 15:37:43
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

import datetime
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import model2protobuf, pool, protobuf2model
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Dict, List, Optional, Type


class ApiKey(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    name: Optional[str] = _Field(default="")
    key: Optional[str] = _Field(default="")
    user_id: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    scopes: Optional[List[str]] = _Field(default=[])
    created_at: Optional[datetime.datetime] = _Field(default=None)
    expires_at: Optional[datetime.datetime] = _Field(default=None)
    last_used_at: Optional[datetime.datetime] = _Field(default=None)
    is_active: Optional[bool] = _Field(default=False)
    metadata: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ApiKey")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ApiKey":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreateApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    name: Optional[str] = _Field(default="")
    user_id: Optional[str] = _Field(default="")
    scopes: Optional[List[str]] = _Field(default=[])
    expires_at: Optional[datetime.datetime] = _Field(default=None)
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    description: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreateApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreateApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListApiKeysRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    user_id: Optional[str] = _Field(default="")
    page: Optional[int] = _Field(default=0)
    limit: Optional[int] = _Field(default=0)
    include_inactive: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListApiKeysRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListApiKeysRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpdateApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    name: Optional[str] = _Field(default="")
    scopes: Optional[List[str]] = _Field(default=[])
    expires_at: Optional[datetime.datetime] = _Field(default=None)
    is_active: Optional[bool] = _Field(default=False)
    metadata: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UpdateApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpdateApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeleteApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeleteApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeleteApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ValidateApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    api_key: Optional[str] = _Field(default="")
    required_scopes: Optional[List[str]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ValidateApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ValidateApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RotateApiKeyRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RotateApiKeyRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RotateApiKeyRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreateApiKeyResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    api_key: Optional["ApiKey"] = _Field(default=None)
    raw_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreateApiKeyResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreateApiKeyResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListApiKeysResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    api_keys: Optional[List["ApiKey"]] = _Field(default=[])
    total: Optional[int] = _Field(default=0)
    page: Optional[int] = _Field(default=0)
    limit: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListApiKeysResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListApiKeysResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ValidateApiKeyResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    is_valid: Optional[bool] = _Field(default=False)
    api_key: Optional["ApiKey"] = _Field(default=None)
    error_message: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ValidateApiKeyResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ValidateApiKeyResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RotateApiKeyResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    api_key: Optional["ApiKey"] = _Field(default=None)
    raw_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RotateApiKeyResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RotateApiKeyResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


ApiKey.model_rebuild()
CreateApiKeyRequest.model_rebuild()
ListApiKeysRequest.model_rebuild()
GetApiKeyRequest.model_rebuild()
UpdateApiKeyRequest.model_rebuild()
DeleteApiKeyRequest.model_rebuild()
ValidateApiKeyRequest.model_rebuild()
RotateApiKeyRequest.model_rebuild()
CreateApiKeyResponse.model_rebuild()
ListApiKeysResponse.model_rebuild()
ValidateApiKeyResponse.model_rebuild()
RotateApiKeyResponse.model_rebuild()
