# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import audit_pb2 as audit__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """审计日志服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuditLogs = channel.unary_unary(
                '/stew.api.v1.AuditService/GetAuditLogs',
                request_serializer=audit__pb2.GetAuditLogsRequest.SerializeToString,
                response_deserializer=audit__pb2.GetAuditLogsResponse.FromString,
                _registered_method=True)
        self.GetAuditStatistics = channel.unary_unary(
                '/stew.api.v1.AuditService/GetAuditStatistics',
                request_serializer=audit__pb2.GetAuditStatisticsRequest.SerializeToString,
                response_deserializer=audit__pb2.GetAuditStatisticsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """审计日志服务
    """

    def GetAuditLogs(self, request, context):
        """获取审计日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditStatistics(self, request, context):
        """获取审计统计信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLogs,
                    request_deserializer=audit__pb2.GetAuditLogsRequest.FromString,
                    response_serializer=audit__pb2.GetAuditLogsResponse.SerializeToString,
            ),
            'GetAuditStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditStatistics,
                    request_deserializer=audit__pb2.GetAuditStatisticsRequest.FromString,
                    response_serializer=audit__pb2.GetAuditStatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stew.api.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stew.api.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """审计日志服务
    """

    @staticmethod
    def GetAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.AuditService/GetAuditLogs',
            audit__pb2.GetAuditLogsRequest.SerializeToString,
            audit__pb2.GetAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.AuditService/GetAuditStatistics',
            audit__pb2.GetAuditStatisticsRequest.SerializeToString,
            audit__pb2.GetAuditStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
