# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   billing_public_model.py
@Time    :   2026-06-12 15:09:15
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

from .billing_common_model import BalanceSnapshot, BillingSubjectType
from .entitlement_model import ResolvedEntitlementResponse
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import model2protobuf, pool, protobuf2model
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Optional, Type


class GetAccountStatusRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    subject_type: Optional[BillingSubjectType] = _Field(default=BillingSubjectType(0))
    user_id: Optional[str] = _Field(default="")
    include_entitlement: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetAccountStatusRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetAccountStatusRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class AccountStatusResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    balance: Optional[BalanceSnapshot] = _Field(default=None)
    effective_available_balance: Optional[int] = _Field(default=0)
    entitlement: Optional[ResolvedEntitlementResponse] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.AccountStatusResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "AccountStatusResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


GetAccountStatusRequest.model_rebuild()
AccountStatusResponse.model_rebuild()
