# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   billing_public_model.py
@Time    :   2026-05-28 17:01:46
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations
