# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   billing_strategy_admin_model.py
@Time    :   2026-05-21 09:49:23
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

import datetime
from .billing_common_model import BillingPolicyArtifactType, ServiceBillingConfig
from .entitlement_model import CreatePlanRequest
from enum import Enum as _Enum
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import (
    GenericEnumType,
    model2protobuf,
    pool,
    protobuf2model,
)
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Any, Dict, List, Optional, Type


class StrategyPackageSection(_Enum):
    STRATEGY_PACKAGE_SECTION_UNSPECIFIED = 0
    STRATEGY_PACKAGE_SECTION_ENTITLEMENT_PLANS = 1
    STRATEGY_PACKAGE_SECTION_BILLING_POLICIES = 2
    STRATEGY_PACKAGE_SECTION_SERVICE_BINDINGS = 3
    STRATEGY_PACKAGE_SECTION_PRICING_VIEWS = 4


StrategyPackageSectionType = GenericEnumType(
    StrategyPackageSection,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyPackageSectionNameType = GenericEnumType(
    StrategyPackageSection,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyImportMode(_Enum):
    STRATEGY_IMPORT_MODE_UNSPECIFIED = 0
    STRATEGY_IMPORT_MODE_CREATE_MISSING_ONLY = 1
    STRATEGY_IMPORT_MODE_UPSERT_MUTABLE_OBJECTS = 2
    STRATEGY_IMPORT_MODE_FAIL_IF_EXISTS = 3


StrategyImportModeType = GenericEnumType(
    StrategyImportMode,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyImportModeNameType = GenericEnumType(
    StrategyImportMode,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyImportConflictPolicy(_Enum):
    STRATEGY_IMPORT_CONFLICT_POLICY_UNSPECIFIED = 0
    STRATEGY_IMPORT_CONFLICT_POLICY_FAIL = 1
    STRATEGY_IMPORT_CONFLICT_POLICY_SKIP_REUSABLE = 2
    STRATEGY_IMPORT_CONFLICT_POLICY_APPLY_MUTABLE_PATCH_ONLY = 3


StrategyImportConflictPolicyType = GenericEnumType(
    StrategyImportConflictPolicy,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyImportConflictPolicyNameType = GenericEnumType(
    StrategyImportConflictPolicy,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyPackageDiagnosticSeverity(_Enum):
    STRATEGY_PACKAGE_DIAGNOSTIC_SEVERITY_UNSPECIFIED = 0
    STRATEGY_PACKAGE_DIAGNOSTIC_SEVERITY_INFO = 1
    STRATEGY_PACKAGE_DIAGNOSTIC_SEVERITY_WARNING = 2
    STRATEGY_PACKAGE_DIAGNOSTIC_SEVERITY_ERROR = 3


StrategyPackageDiagnosticSeverityType = GenericEnumType(
    StrategyPackageDiagnosticSeverity,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyPackageDiagnosticSeverityNameType = GenericEnumType(
    StrategyPackageDiagnosticSeverity,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyImportAction(_Enum):
    STRATEGY_IMPORT_ACTION_UNSPECIFIED = 0
    STRATEGY_IMPORT_ACTION_CREATE = 1
    STRATEGY_IMPORT_ACTION_UPDATE = 2
    STRATEGY_IMPORT_ACTION_REUSE = 3
    STRATEGY_IMPORT_ACTION_PUBLISH = 4
    STRATEGY_IMPORT_ACTION_SKIP = 5
    STRATEGY_IMPORT_ACTION_CONFLICT = 6
    STRATEGY_IMPORT_ACTION_NOOP = 7


StrategyImportActionType = GenericEnumType(
    StrategyImportAction,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyImportActionNameType = GenericEnumType(
    StrategyImportAction,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyPackageObjectType(_Enum):
    STRATEGY_PACKAGE_OBJECT_TYPE_UNSPECIFIED = 0
    STRATEGY_PACKAGE_OBJECT_TYPE_PLAN = 1
    STRATEGY_PACKAGE_OBJECT_TYPE_POLICY = 2
    STRATEGY_PACKAGE_OBJECT_TYPE_ARTIFACT = 3
    STRATEGY_PACKAGE_OBJECT_TYPE_BUNDLE = 4
    STRATEGY_PACKAGE_OBJECT_TYPE_SERVICE_BINDING = 5
    STRATEGY_PACKAGE_OBJECT_TYPE_PRICING_VIEW = 6


StrategyPackageObjectTypeType = GenericEnumType(
    StrategyPackageObjectType,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyPackageObjectTypeNameType = GenericEnumType(
    StrategyPackageObjectType,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyImportJobStatus(_Enum):
    STRATEGY_IMPORT_JOB_STATUS_UNSPECIFIED = 0
    STRATEGY_IMPORT_JOB_STATUS_PENDING = 1
    STRATEGY_IMPORT_JOB_STATUS_RUNNING = 2
    STRATEGY_IMPORT_JOB_STATUS_SUCCEEDED = 3
    STRATEGY_IMPORT_JOB_STATUS_FAILED = 4


StrategyImportJobStatusType = GenericEnumType(
    StrategyImportJobStatus,
    storage_mode="value",
    read_modes=("value", "name"),
)

StrategyImportJobStatusNameType = GenericEnumType(
    StrategyImportJobStatus,
    storage_mode="name",
    read_modes=("name", "value"),
)


class StrategyPackageExportScope(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    strategy_key: Optional[str] = _Field(default="")
    sections: Optional[List["StrategyPackageSection"]] = _Field(default=[])
    include_archived: Optional[bool] = _Field(default=False)
    include_inactive_bundles: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageExportScope")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageExportScope":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageSource(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    exporter: Optional[str] = _Field(default="")
    exporter_version: Optional[str] = _Field(default="")
    workspace: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageSource")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageSource":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageIdPolicy(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    plan_identity: Optional[str] = _Field(default="")
    policy_identity: Optional[str] = _Field(default="")
    artifact_identity: Optional[str] = _Field(default="")
    bundle_identity: Optional[str] = _Field(default="")
    binding_identity: Optional[str] = _Field(default="")
    runtime_refs_are_authoritative: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageIdPolicy")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageIdPolicy":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePlanRuntimeRefs(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    plan_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackagePlanRuntimeRefs"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePlanRuntimeRefs":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePlanMetadataContract(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    billing_model: Optional[str] = _Field(default="")
    price_keys: Optional[List[str]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackagePlanMetadataContract"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(
        cls, src: _message.Message
    ) -> "StrategyPackagePlanMetadataContract":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePolicyRuntimeRefs(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    policy_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackagePolicyRuntimeRefs"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePolicyRuntimeRefs":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePolicyInfo(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    display_name: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    status: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackagePolicyInfo")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePolicyInfo":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageArtifactRuntimeRefs(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    artifact_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackageArtifactRuntimeRefs"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(
        cls, src: _message.Message
    ) -> "StrategyPackageArtifactRuntimeRefs":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageBundleRuntimeRefs(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    published_bundle_version: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackageBundleRuntimeRefs"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageBundleRuntimeRefs":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageBundleArtifactRefs(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    provider_rate_card: Optional[str] = _Field(default="")
    point_policy: Optional[str] = _Field(default="")
    money_policy: Optional[str] = _Field(default="")
    estimator: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackageBundleArtifactRefs"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(
        cls, src: _message.Message
    ) -> "StrategyPackageBundleArtifactRefs":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePolicyRef(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    policy_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackagePolicyRef")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePolicyRef":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePricingView(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    pricing_view_key: Optional[str] = _Field(default="")
    asset_space: Optional[str] = _Field(default="")
    document_path: Optional[str] = _Field(default="")
    content: Optional[Dict[str, Any]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackagePricingView")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePricingView":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageIntegrity(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    hash_algorithm: Optional[str] = _Field(default="")
    package_hash: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageIntegrity")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageIntegrity":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ExportStrategyPackageRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    sections: Optional[List["StrategyPackageSection"]] = _Field(default=[])
    strategy_key: Optional[str] = _Field(default="")
    include_archived: Optional[bool] = _Field(default=False)
    include_inactive_bundles: Optional[bool] = _Field(default=False)
    include_pricing_views: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ExportStrategyPackageRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ExportStrategyPackageRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetStrategyImportJobRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    job_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetStrategyImportJobRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetStrategyImportJobRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageDiagnostic(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    severity: Optional["StrategyPackageDiagnosticSeverity"] = _Field(
        default=StrategyPackageDiagnosticSeverity(0)
    )
    code: Optional[str] = _Field(default="")
    path: Optional[str] = _Field(default="")
    message: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageDiagnostic")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageDiagnostic":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportPlanItem(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    object_type: Optional["StrategyPackageObjectType"] = _Field(
        default=StrategyPackageObjectType(0)
    )
    stable_key: Optional[str] = _Field(default="")
    path: Optional[str] = _Field(default="")
    planned_action: Optional["StrategyImportAction"] = _Field(
        default=StrategyImportAction(0)
    )
    message: Optional[str] = _Field(default="")
    depends_on_keys: Optional[List[str]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportPlanItem")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportPlanItem":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportCounts(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    create_count: Optional[int] = _Field(default=0)
    update_count: Optional[int] = _Field(default=0)
    reuse_count: Optional[int] = _Field(default=0)
    publish_count: Optional[int] = _Field(default=0)
    skip_count: Optional[int] = _Field(default=0)
    conflict_count: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportCounts")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportCounts":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportObjectResult(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    object_type: Optional["StrategyPackageObjectType"] = _Field(
        default=StrategyPackageObjectType(0)
    )
    stable_key: Optional[str] = _Field(default="")
    path: Optional[str] = _Field(default="")
    action: Optional["StrategyImportAction"] = _Field(default=StrategyImportAction(0))
    runtime_id: Optional[str] = _Field(default="")
    message: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportObjectResult")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportObjectResult":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePlan(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    plan_key: Optional[str] = _Field(default="")
    plan_code: Optional[str] = _Field(default="")
    runtime_refs: Optional["StrategyPackagePlanRuntimeRefs"] = _Field(default=None)
    create_plan_request: Optional[CreatePlanRequest] = _Field(default=None)
    metadata_contract: Optional["StrategyPackagePlanMetadataContract"] = _Field(
        default=None
    )

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackagePlan")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePlan":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageArtifact(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    artifact_key: Optional[str] = _Field(default="")
    runtime_refs: Optional["StrategyPackageArtifactRuntimeRefs"] = _Field(default=None)
    artifact_type: Optional[BillingPolicyArtifactType] = _Field(
        default=BillingPolicyArtifactType(0)
    )
    artifact_version: Optional[str] = _Field(default="")
    content_hash: Optional[str] = _Field(default="")
    content: Optional[Dict[str, Any]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageArtifact")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageArtifact":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageBundle(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    bundle_key: Optional[str] = _Field(default="")
    bundle_version: Optional[int] = _Field(default=0)
    status: Optional[str] = _Field(default="")
    factor_schema_version: Optional[str] = _Field(default="")
    artifact_refs: Optional["StrategyPackageBundleArtifactRefs"] = _Field(default=None)
    runtime_refs: Optional["StrategyPackageBundleRuntimeRefs"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageBundle")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageBundle":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePlanPolicyOverride(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    plan_key: Optional[str] = _Field(default="")
    policy_ref: Optional["StrategyPackagePolicyRef"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.StrategyPackagePlanPolicyOverride"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(
        cls, src: _message.Message
    ) -> "StrategyPackagePlanPolicyOverride":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportPlan(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    items: Optional[List["StrategyImportPlanItem"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportPlan")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportPlan":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportResult(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    objects: Optional[List["StrategyImportObjectResult"]] = _Field(default=[])
    counts: Optional["StrategyImportCounts"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportResult")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportResult":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackagePolicy(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    policy_key: Optional[str] = _Field(default="")
    runtime_refs: Optional["StrategyPackagePolicyRuntimeRefs"] = _Field(default=None)
    policy: Optional["StrategyPackagePolicyInfo"] = _Field(default=None)
    artifacts: Optional[List["StrategyPackageArtifact"]] = _Field(default=[])
    bundles: Optional[List["StrategyPackageBundle"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackagePolicy")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackagePolicy":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyPackageServiceBinding(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    binding_key: Optional[str] = _Field(default="")
    service_name: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    default_policy_ref: Optional["StrategyPackagePolicyRef"] = _Field(default=None)
    policy_overrides_by_plan: Optional[List["StrategyPackagePlanPolicyOverride"]] = (
        _Field(default=[])
    )
    service_billing_config_patch: Optional[ServiceBillingConfig] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyPackageServiceBinding")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyPackageServiceBinding":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ValidateStrategyPackageResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    success: Optional[bool] = _Field(default=False)
    diagnostics: Optional[List["StrategyPackageDiagnostic"]] = _Field(default=[])
    plan: Optional["StrategyImportPlan"] = _Field(default=None)
    summary: Optional["StrategyImportCounts"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.ValidateStrategyPackageResponse"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ValidateStrategyPackageResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ImportStrategyPackageResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    success: Optional[bool] = _Field(default=False)
    import_job_id: Optional[str] = _Field(default="")
    diagnostics: Optional[List["StrategyPackageDiagnostic"]] = _Field(default=[])
    plan: Optional["StrategyImportPlan"] = _Field(default=None)
    result: Optional["StrategyImportResult"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ImportStrategyPackageResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ImportStrategyPackageResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class StrategyImportJob(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    job_id: Optional[str] = _Field(default="")
    status: Optional["StrategyImportJobStatus"] = _Field(
        default=StrategyImportJobStatus(0)
    )
    dry_run: Optional[bool] = _Field(default=False)
    mode: Optional["StrategyImportMode"] = _Field(default=StrategyImportMode(0))
    conflict_policy: Optional["StrategyImportConflictPolicy"] = _Field(
        default=StrategyImportConflictPolicy(0)
    )
    created_at: Optional[datetime.datetime] = _Field(default=None)
    started_at: Optional[datetime.datetime] = _Field(default=None)
    completed_at: Optional[datetime.datetime] = _Field(default=None)
    plan: Optional["StrategyImportPlan"] = _Field(default=None)
    result: Optional["StrategyImportResult"] = _Field(default=None)
    diagnostics: Optional[List["StrategyPackageDiagnostic"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.StrategyImportJob")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "StrategyImportJob":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class BillingStrategyPackage(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    document_type: Optional[str] = _Field(default="")
    schema_version: Optional[str] = _Field(default="")
    exported_at: Optional[datetime.datetime] = _Field(default=None)
    export_scope: Optional["StrategyPackageExportScope"] = _Field(default=None)
    source: Optional["StrategyPackageSource"] = _Field(default=None)
    id_policy: Optional["StrategyPackageIdPolicy"] = _Field(default=None)
    entitlement_plans: Optional[List["StrategyPackagePlan"]] = _Field(default=[])
    billing_policies: Optional[List["StrategyPackagePolicy"]] = _Field(default=[])
    service_bindings: Optional[List["StrategyPackageServiceBinding"]] = _Field(
        default=[]
    )
    pricing_views: Optional[List["StrategyPackagePricingView"]] = _Field(default=[])
    integrity: Optional["StrategyPackageIntegrity"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.BillingStrategyPackage")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "BillingStrategyPackage":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ValidateStrategyPackageRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    package: Optional["BillingStrategyPackage"] = _Field(default=None)
    allow_partial_sections: Optional[bool] = _Field(default=False)
    allow_runtime_ref_mismatch: Optional[bool] = _Field(default=False)
    conflict_policy: Optional["StrategyImportConflictPolicy"] = _Field(
        default=StrategyImportConflictPolicy(0)
    )

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.ValidateStrategyPackageRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ValidateStrategyPackageRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ImportStrategyPackageRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    package: Optional["BillingStrategyPackage"] = _Field(default=None)
    mode: Optional["StrategyImportMode"] = _Field(default=StrategyImportMode(0))
    conflict_policy: Optional["StrategyImportConflictPolicy"] = _Field(
        default=StrategyImportConflictPolicy(0)
    )
    dry_run: Optional[bool] = _Field(default=False)
    allow_partial_sections: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ImportStrategyPackageRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ImportStrategyPackageRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ExportStrategyPackageResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    package: Optional["BillingStrategyPackage"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ExportStrategyPackageResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ExportStrategyPackageResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


StrategyPackageExportScope.model_rebuild()
StrategyPackageSource.model_rebuild()
StrategyPackageIdPolicy.model_rebuild()
StrategyPackagePlanRuntimeRefs.model_rebuild()
StrategyPackagePlanMetadataContract.model_rebuild()
StrategyPackagePolicyRuntimeRefs.model_rebuild()
StrategyPackagePolicyInfo.model_rebuild()
StrategyPackageArtifactRuntimeRefs.model_rebuild()
StrategyPackageBundleRuntimeRefs.model_rebuild()
StrategyPackageBundleArtifactRefs.model_rebuild()
StrategyPackagePolicyRef.model_rebuild()
StrategyPackagePricingView.model_rebuild()
StrategyPackageIntegrity.model_rebuild()
ExportStrategyPackageRequest.model_rebuild()
GetStrategyImportJobRequest.model_rebuild()
StrategyPackageDiagnostic.model_rebuild()
StrategyImportPlanItem.model_rebuild()
StrategyImportCounts.model_rebuild()
StrategyImportObjectResult.model_rebuild()
StrategyPackagePlan.model_rebuild()
StrategyPackageArtifact.model_rebuild()
StrategyPackageBundle.model_rebuild()
StrategyPackagePlanPolicyOverride.model_rebuild()
StrategyImportPlan.model_rebuild()
StrategyImportResult.model_rebuild()
StrategyPackagePolicy.model_rebuild()
StrategyPackageServiceBinding.model_rebuild()
ValidateStrategyPackageResponse.model_rebuild()
ImportStrategyPackageResponse.model_rebuild()
StrategyImportJob.model_rebuild()
BillingStrategyPackage.model_rebuild()
ValidateStrategyPackageRequest.model_rebuild()
ImportStrategyPackageRequest.model_rebuild()
ExportStrategyPackageResponse.model_rebuild()
