# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   business_membership_admin_model.py
@Time    :   2026-05-24 03:45:21
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import model2protobuf, pool, protobuf2model
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import List, Optional, Type


class BusinessMembershipRecord(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    business_name: Optional[str] = _Field(default="")
    business_status: Optional[str] = _Field(default="")
    external_source_type: Optional[str] = _Field(default="")
    external_source_ref: Optional[str] = _Field(default="")
    local_user_id: Optional[int] = _Field(default=0)
    membership_status: Optional[str] = _Field(default="")
    role_codes: Optional[List[str]] = _Field(default=[])
    source_type: Optional[str] = _Field(default="")
    source_subject: Optional[str] = _Field(default="")
    source_version: Optional[str] = _Field(default="")
    created_at: Optional[str] = _Field(default="")
    updated_at: Optional[str] = _Field(default="")
    synced_at: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.BusinessMembershipRecord")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "BusinessMembershipRecord":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListBusinessMembershipsRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    local_user_id: Optional[int] = _Field(default=0)
    membership_status: Optional[str] = _Field(default="")
    page_size: Optional[int] = _Field(default=0)
    page_offset: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.ListBusinessMembershipsRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListBusinessMembershipsRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetBusinessMembershipRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    local_user_id: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetBusinessMembershipRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetBusinessMembershipRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpsertBusinessMembershipRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    local_user_id: Optional[int] = _Field(default=0)
    business_name: Optional[str] = _Field(default="")
    business_status: Optional[str] = _Field(default="")
    external_source_type: Optional[str] = _Field(default="")
    external_source_ref: Optional[str] = _Field(default="")
    membership_status: Optional[str] = _Field(default="")
    role_codes: Optional[List[str]] = _Field(default=[])
    source_type: Optional[str] = _Field(default="")
    source_subject: Optional[str] = _Field(default="")
    source_version: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.UpsertBusinessMembershipRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpsertBusinessMembershipRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeleteBusinessMembershipRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    local_user_id: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.DeleteBusinessMembershipRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeleteBusinessMembershipRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeleteBusinessMembershipResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    deleted: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.DeleteBusinessMembershipResponse"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeleteBusinessMembershipResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListBusinessMembershipsResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    items: Optional[List["BusinessMembershipRecord"]] = _Field(default=[])
    total_size: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.ListBusinessMembershipsResponse"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListBusinessMembershipsResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


BusinessMembershipRecord.model_rebuild()
ListBusinessMembershipsRequest.model_rebuild()
GetBusinessMembershipRequest.model_rebuild()
UpsertBusinessMembershipRequest.model_rebuild()
DeleteBusinessMembershipRequest.model_rebuild()
DeleteBusinessMembershipResponse.model_rebuild()
ListBusinessMembershipsResponse.model_rebuild()
