# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   entitlement_model.py
@Time    :   2026-06-12 17:52:06
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

import datetime
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import model2protobuf, pool, protobuf2model
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Any, Dict, List, Optional, Type


class PlanFeature(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    feature_key: Optional[str] = _Field(default="")
    enabled: Optional[bool] = _Field(default=False)
    config: Optional[Dict[str, Any]] = _Field(default=None)
    feature_display_name: Optional[str] = _Field(default="")
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)
    localized_display_name: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PlanFeature")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PlanFeature":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PlanQuota(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    quota_key: Optional[str] = _Field(default="")
    quota_limit: Optional[int] = _Field(default=0)
    quota_unit: Optional[str] = _Field(default="")
    reset_period: Optional[str] = _Field(default="")
    quota_display_name: Optional[str] = _Field(default="")
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)
    localized_display_name: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PlanQuota")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PlanQuota":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class Subscription(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    subject_type: Optional[int] = _Field(default=0)
    plan_id: Optional[str] = _Field(default="")
    status: Optional[str] = _Field(default="")
    billing_cycle: Optional[str] = _Field(default="")
    current_period_start: Optional[int] = _Field(default=0)
    current_period_end: Optional[int] = _Field(default=0)
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.Subscription")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "Subscription":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class QuotaUsage(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    quota_key: Optional[str] = _Field(default="")
    period_start: Optional[int] = _Field(default=0)
    period_end: Optional[int] = _Field(default=0)
    used: Optional[int] = _Field(default=0)
    quota_display_name: Optional[str] = _Field(default="")
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)
    localized_display_name: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.QuotaUsage")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "QuotaUsage":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetPlanRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetPlanRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetPlanRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPlansRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    active_only: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPlansRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPlansRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreateSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    subject_type: Optional[int] = _Field(default=0)
    plan_id: Optional[str] = _Field(default="")
    billing_cycle: Optional[str] = _Field(default="")
    current_period_start: Optional[int] = _Field(default=0)
    current_period_end: Optional[int] = _Field(default=0)
    metadata: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreateSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreateSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetSubscriptionBySubjectRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.GetSubscriptionBySubjectRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetSubscriptionBySubjectRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpdateSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    status: Optional[str] = _Field(default="")
    billing_cycle: Optional[str] = _Field(default="")
    current_period_start: Optional[int] = _Field(default=0)
    current_period_end: Optional[int] = _Field(default=0)
    metadata: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UpdateSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpdateSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CancelSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CancelSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CancelSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeleteSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeleteSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeleteSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RestoreSubscriptionRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RestoreSubscriptionRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RestoreSubscriptionRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListSubscriptionsRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    status: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")
    include_deleted: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListSubscriptionsRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListSubscriptionsRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RenewSubscriptionsRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    subscription_ids: Optional[List[str]] = _Field(default=[])
    horizon_seconds: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RenewSubscriptionsRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RenewSubscriptionsRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeletePlanRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeletePlanRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeletePlanRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeletePlanFeatureRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    feature_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeletePlanFeatureRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeletePlanFeatureRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeletePlanQuotaRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    quota_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeletePlanQuotaRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeletePlanQuotaRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetQuotaUsageRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    quota_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetQuotaUsageRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetQuotaUsageRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class IncrementQuotaRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    quota_key: Optional[str] = _Field(default="")
    delta: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.IncrementQuotaRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "IncrementQuotaRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CheckQuotaRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    quota_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CheckQuotaRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CheckQuotaRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CheckQuotaResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    used: Optional[int] = _Field(default=0)
    limit: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CheckQuotaResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CheckQuotaResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PlanChangeRecord(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    previous_plan_id: Optional[str] = _Field(default="")
    new_plan_id: Optional[str] = _Field(default="")
    change_type: Optional[str] = _Field(default="")
    change_mode: Optional[str] = _Field(default="")
    status: Optional[str] = _Field(default="")
    effective_at: Optional[int] = _Field(default=0)
    executed_at: Optional[int] = _Field(default=0)
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PlanChangeRecord")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PlanChangeRecord":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ChangePlanRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    new_plan_id: Optional[str] = _Field(default="")
    change_mode: Optional[str] = _Field(default="")
    reset_quota: Optional[bool] = _Field(default=False)
    metadata: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ChangePlanRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ChangePlanRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPlanChangesRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subscription_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPlanChangesRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPlanChangesRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CancelPlanChangeRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    change_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CancelPlanChangeRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CancelPlanChangeRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetMyEntitlementRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetMyEntitlementRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetMyEntitlementRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CheckFeatureRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    feature_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CheckFeatureRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CheckFeatureRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CheckFeatureResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    enabled: Optional[bool] = _Field(default=False)
    feature_key: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    config: Optional[Dict[str, Any]] = _Field(default=None)
    feature_display_name: Optional[str] = _Field(default="")
    localized_display_name: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CheckFeatureResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CheckFeatureResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpsertPlanFeatureRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    feature: Optional["PlanFeature"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UpsertPlanFeatureRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpsertPlanFeatureRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class EntitlementPlan(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    name: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    is_active: Optional[bool] = _Field(default=False)
    sort_order: Optional[int] = _Field(default=0)
    features: Optional[List["PlanFeature"]] = _Field(default=[])
    quotas: Optional[List["PlanQuota"]] = _Field(default=[])
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    deleted_at: Optional[datetime.datetime] = _Field(default=None)
    localized_name: Optional[Dict[str, str]] = _Field(default=None)
    localized_description: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.EntitlementPlan")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "EntitlementPlan":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreatePlanRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    name: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    is_active: Optional[bool] = _Field(default=False)
    sort_order: Optional[int] = _Field(default=0)
    features: Optional[List["PlanFeature"]] = _Field(default=[])
    quotas: Optional[List["PlanQuota"]] = _Field(default=[])
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    localized_name: Optional[Dict[str, str]] = _Field(default=None)
    localized_description: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreatePlanRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreatePlanRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpdatePlanRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    name: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    is_active: Optional[bool] = _Field(default=False)
    sort_order: Optional[int] = _Field(default=0)
    features: Optional[List["PlanFeature"]] = _Field(default=[])
    quotas: Optional[List["PlanQuota"]] = _Field(default=[])
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    localized_name: Optional[Dict[str, str]] = _Field(default=None)
    localized_description: Optional[Dict[str, str]] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UpdatePlanRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpdatePlanRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UpsertPlanQuotaRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    quota: Optional["PlanQuota"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UpsertPlanQuotaRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UpsertPlanQuotaRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListSubscriptionsResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    subscriptions: Optional[List["Subscription"]] = _Field(default=[])
    next_page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListSubscriptionsResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListSubscriptionsResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RenewSubscriptionResult(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    subscription_id: Optional[str] = _Field(default="")
    succeeded: Optional[bool] = _Field(default=False)
    error_message: Optional[str] = _Field(default="")
    subscription: Optional["Subscription"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RenewSubscriptionResult")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RenewSubscriptionResult":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ChangePlanResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    subscription: Optional["Subscription"] = _Field(default=None)
    change_record: Optional["PlanChangeRecord"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ChangePlanResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ChangePlanResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPlanChangesResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    changes: Optional[List["PlanChangeRecord"]] = _Field(default=[])
    next_page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPlanChangesResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPlanChangesResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPlansResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    plans: Optional[List["EntitlementPlan"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPlansResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPlansResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ResolvedEntitlementResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    subscription: Optional["Subscription"] = _Field(default=None)
    plan: Optional["EntitlementPlan"] = _Field(default=None)
    quota_usages: Optional[List["QuotaUsage"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ResolvedEntitlementResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ResolvedEntitlementResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RenewSubscriptionsResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    results: Optional[List["RenewSubscriptionResult"]] = _Field(default=[])
    succeeded_count: Optional[int] = _Field(default=0)
    failed_count: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RenewSubscriptionsResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RenewSubscriptionsResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


PlanFeature.model_rebuild()
PlanQuota.model_rebuild()
Subscription.model_rebuild()
QuotaUsage.model_rebuild()
GetPlanRequest.model_rebuild()
ListPlansRequest.model_rebuild()
CreateSubscriptionRequest.model_rebuild()
GetSubscriptionRequest.model_rebuild()
GetSubscriptionBySubjectRequest.model_rebuild()
UpdateSubscriptionRequest.model_rebuild()
CancelSubscriptionRequest.model_rebuild()
DeleteSubscriptionRequest.model_rebuild()
RestoreSubscriptionRequest.model_rebuild()
ListSubscriptionsRequest.model_rebuild()
RenewSubscriptionsRequest.model_rebuild()
DeletePlanRequest.model_rebuild()
DeletePlanFeatureRequest.model_rebuild()
DeletePlanQuotaRequest.model_rebuild()
GetQuotaUsageRequest.model_rebuild()
IncrementQuotaRequest.model_rebuild()
CheckQuotaRequest.model_rebuild()
CheckQuotaResponse.model_rebuild()
PlanChangeRecord.model_rebuild()
ChangePlanRequest.model_rebuild()
ListPlanChangesRequest.model_rebuild()
CancelPlanChangeRequest.model_rebuild()
GetMyEntitlementRequest.model_rebuild()
CheckFeatureRequest.model_rebuild()
CheckFeatureResponse.model_rebuild()
UpsertPlanFeatureRequest.model_rebuild()
EntitlementPlan.model_rebuild()
CreatePlanRequest.model_rebuild()
UpdatePlanRequest.model_rebuild()
UpsertPlanQuotaRequest.model_rebuild()
ListSubscriptionsResponse.model_rebuild()
RenewSubscriptionResult.model_rebuild()
ChangePlanResponse.model_rebuild()
ListPlanChangesResponse.model_rebuild()
ListPlansResponse.model_rebuild()
ResolvedEntitlementResponse.model_rebuild()
RenewSubscriptionsResponse.model_rebuild()
