# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   file_storage_model.py
@Time    :   2026-04-20 13:40:28
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

import datetime
from enum import Enum as _Enum
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import (
    GenericEnumType,
    model2protobuf,
    pool,
    protobuf2model,
)
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import List, Optional, Type


class UploadSessionStatus(_Enum):
    UPLOAD_SESSION_STATUS_UNSPECIFIED = 0
    UPLOAD_SESSION_STATUS_ACTIVE = 1
    UPLOAD_SESSION_STATUS_COMPLETED = 2
    UPLOAD_SESSION_STATUS_ABORTED = 3


UploadSessionStatusType = GenericEnumType(
    UploadSessionStatus,
    storage_mode="value",
    read_modes=("value", "name"),
)

UploadSessionStatusNameType = GenericEnumType(
    UploadSessionStatus,
    storage_mode="name",
    read_modes=("name", "value"),
)


class PathEntryKind(_Enum):
    PATH_ENTRY_KIND_UNSPECIFIED = 0
    PATH_ENTRY_KIND_FILE = 1
    PATH_ENTRY_KIND_DIRECTORY = 2


PathEntryKindType = GenericEnumType(
    PathEntryKind,
    storage_mode="value",
    read_modes=("value", "name"),
)

PathEntryKindNameType = GenericEnumType(
    PathEntryKind,
    storage_mode="name",
    read_modes=("name", "value"),
)


class UploadFileMetadata(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    filename: Optional[str] = _Field(default="")
    content_type: Optional[str] = _Field(default="")
    folder: Optional[str] = _Field(default="")
    business_context: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadFileMetadata")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadFileMetadata":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class InitResumableUploadRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    filename: Optional[str] = _Field(default="")
    content_type: Optional[str] = _Field(default="")
    folder: Optional[str] = _Field(default="")
    total_size: Optional[int] = _Field(default=0)
    part_size: Optional[int] = _Field(default=0)
    business_context: Optional[str] = _Field(default="")
    checksum: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.InitResumableUploadRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "InitResumableUploadRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class InitResumableUploadResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")
    part_size: Optional[int] = _Field(default=0)
    total_parts: Optional[int] = _Field(default=0)
    expires_at: Optional[datetime.datetime] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.InitResumableUploadResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "InitResumableUploadResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadPartHeader(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")
    part_number: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadPartHeader")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadPartHeader":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadPartResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    part_number: Optional[int] = _Field(default=0)
    etag: Optional[str] = _Field(default="")
    bytes_written: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadPartResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadPartResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PartEtag(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    part_number: Optional[int] = _Field(default=0)
    etag: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PartEtag")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PartEtag":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class AbortResumableUploadRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.AbortResumableUploadRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "AbortResumableUploadRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetUploadStatusRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetUploadStatusRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetUploadStatusRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadedPartInfo(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    part_number: Optional[int] = _Field(default=0)
    etag: Optional[str] = _Field(default="")
    size: Optional[int] = _Field(default=0)
    completed_at: Optional[datetime.datetime] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadedPartInfo")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadedPartInfo":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DownloadFileRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    file_id: Optional[str] = _Field(default="")
    checksum: Optional[str] = _Field(default="")
    verify_only: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DownloadFileRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DownloadFileRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DownloadFileHttpMetadata(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    filename: Optional[str] = _Field(default="")
    content_disposition: Optional[str] = _Field(default="")
    etag: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DownloadFileHttpMetadata")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DownloadFileHttpMetadata":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DownloadFileChunk(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    data: Optional[bytes] = _Field(default=b"")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DownloadFileChunk")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DownloadFileChunk":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class DeleteFileRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    file_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.DeleteFileRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "DeleteFileRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListFilesRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    folder: Optional[str] = _Field(default="")
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListFilesRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListFilesRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetFileInfoRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    file_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetFileInfoRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetFileInfoRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CallbackResult(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    accepted: Optional[bool] = _Field(default=False)
    business_id: Optional[str] = _Field(default="")
    message: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CallbackResult")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CallbackResult":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class FileInfo(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    filename: Optional[str] = _Field(default="")
    content_type: Optional[str] = _Field(default="")
    file_size: Optional[int] = _Field(default=0)
    folder: Optional[str] = _Field(default="")
    owner_id: Optional[str] = _Field(default="")
    checksum: Optional[str] = _Field(default="")
    storage_backend: Optional[str] = _Field(default="")
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    local_path: Optional[str] = _Field(default="")
    storage_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.FileInfo")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "FileInfo":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class VirtualPathRef(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    folder: Optional[str] = _Field(default="")
    relative_path: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.VirtualPathRef")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "VirtualPathRef":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PathEntry(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    kind: Optional["PathEntryKind"] = _Field(default=PathEntryKind(0))
    name: Optional[str] = _Field(default="")
    path: Optional[str] = _Field(default="")
    parent_folder: Optional[str] = _Field(default="")
    file_id: Optional[str] = _Field(default="")
    content_type: Optional[str] = _Field(default="")
    size_bytes: Optional[int] = _Field(default=0)
    checksum: Optional[str] = _Field(default="")
    created_at: Optional[datetime.datetime] = _Field(default=None)
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    has_children: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PathEntry")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PathEntry":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListFolderRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    folder: Optional[str] = _Field(default="")
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")
    include_files: Optional[bool] = _Field(default=False)
    include_directories: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListFolderRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListFolderRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListFolderResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    entries: Optional[List[PathEntry]] = _Field(default=None)
    next_page_token: Optional[str] = _Field(default="")
    total_count: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListFolderResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListFolderResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadFileRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    metadata: Optional["UploadFileMetadata"] = _Field(default=None)
    chunk_data: Optional[bytes] = _Field(default=b"")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadFileRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadFileRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadPartRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    header: Optional["UploadPartHeader"] = _Field(default=None)
    chunk_data: Optional[bytes] = _Field(default=b"")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadPartRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadPartRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CompleteResumableUploadRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")
    parts: Optional[List["PartEtag"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName(
            "stew.api.v1.CompleteResumableUploadRequest"
        )
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CompleteResumableUploadRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetUploadStatusResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    upload_id: Optional[str] = _Field(default="")
    status: Optional["UploadSessionStatus"] = _Field(default=UploadSessionStatus(0))
    completed_parts: Optional[List["UploadedPartInfo"]] = _Field(default=[])
    total_parts: Optional[int] = _Field(default=0)
    expires_at: Optional[datetime.datetime] = _Field(default=None)
    filename: Optional[str] = _Field(default="")
    total_size: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetUploadStatusResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetUploadStatusResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class UploadFileResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    file_info: Optional["FileInfo"] = _Field(default=None)
    callback_result: Optional["CallbackResult"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.UploadFileResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "UploadFileResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListFilesResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    files: Optional[List["FileInfo"]] = _Field(default=[])
    next_page_token: Optional[str] = _Field(default="")
    total_count: Optional[int] = _Field(default=0)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListFilesResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListFilesResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PathSelector(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    file_id: Optional[str] = _Field(default="")
    path: Optional["VirtualPathRef"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PathSelector")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PathSelector":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetPathInfoResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    entry: Optional["PathEntry"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetPathInfoResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetPathInfoResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ReadTextFileResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    entry: Optional["PathEntry"] = _Field(default=None)
    text: Optional[str] = _Field(default="")
    content_type: Optional[str] = _Field(default="")
    size_bytes: Optional[int] = _Field(default=0)
    checksum: Optional[str] = _Field(default="")
    updated_at: Optional[datetime.datetime] = _Field(default=None)
    truncated: Optional[bool] = _Field(default=False)
    lossy: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ReadTextFileResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ReadTextFileResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetPathInfoRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    selector: Optional["PathSelector"] = _Field(default=None)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetPathInfoRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetPathInfoRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ReadTextFileRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    selector: Optional["PathSelector"] = _Field(default=None)
    max_bytes: Optional[int] = _Field(default=0)
    fail_if_binary: Optional[bool] = _Field(default=False)

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ReadTextFileRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ReadTextFileRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


UploadFileMetadata.model_rebuild()
InitResumableUploadRequest.model_rebuild()
InitResumableUploadResponse.model_rebuild()
UploadPartHeader.model_rebuild()
UploadPartResponse.model_rebuild()
PartEtag.model_rebuild()
AbortResumableUploadRequest.model_rebuild()
GetUploadStatusRequest.model_rebuild()
UploadedPartInfo.model_rebuild()
DownloadFileRequest.model_rebuild()
DownloadFileHttpMetadata.model_rebuild()
DownloadFileChunk.model_rebuild()
DeleteFileRequest.model_rebuild()
ListFilesRequest.model_rebuild()
GetFileInfoRequest.model_rebuild()
CallbackResult.model_rebuild()
FileInfo.model_rebuild()
VirtualPathRef.model_rebuild()
PathEntry.model_rebuild()
ListFolderRequest.model_rebuild()
ListFolderResponse.model_rebuild()
UploadFileRequest.model_rebuild()
UploadPartRequest.model_rebuild()
CompleteResumableUploadRequest.model_rebuild()
GetUploadStatusResponse.model_rebuild()
UploadFileResponse.model_rebuild()
ListFilesResponse.model_rebuild()
PathSelector.model_rebuild()
GetPathInfoResponse.model_rebuild()
ReadTextFileResponse.model_rebuild()
GetPathInfoRequest.model_rebuild()
ReadTextFileRequest.model_rebuild()
