# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   payment_model.py
@Time    :   2026-06-12 15:09:16
@Desc    :   Auto-generated Pydantic models from protobuf definitions.

DO NOT EDIT — regenerated by protoc-gen-pydantic.
"""

from __future__ import annotations

from enum import Enum as _Enum
from google.protobuf import message as _message, message_factory
from protobuf_pydantic_gen.ext import (
    GenericEnumType,
    model2protobuf,
    pool,
    protobuf2model,
)
from pydantic import BaseModel, ConfigDict, Field as _Field
from typing import Any, Dict, List, Optional, Type


class PaymentProviderKind(_Enum):
    PAYMENT_PROVIDER_KIND_UNSPECIFIED = 0
    PAYMENT_PROVIDER_KIND_STRIPE = 1
    PAYMENT_PROVIDER_KIND_CREEM = 2


PaymentProviderKindType = GenericEnumType(
    PaymentProviderKind,
    storage_mode="value",
    read_modes=("value", "name"),
)

PaymentProviderKindNameType = GenericEnumType(
    PaymentProviderKind,
    storage_mode="name",
    read_modes=("name", "value"),
)


class PaymentOrderStatus(_Enum):
    PAYMENT_ORDER_STATUS_UNSPECIFIED = 0
    PAYMENT_ORDER_STATUS_PENDING = 1
    PAYMENT_ORDER_STATUS_PAID = 2
    PAYMENT_ORDER_STATUS_FAILED = 3
    PAYMENT_ORDER_STATUS_REFUNDED = 4
    PAYMENT_ORDER_STATUS_CANCELED = 5
    PAYMENT_ORDER_STATUS_EXPIRED = 6
    PAYMENT_ORDER_STATUS_CREATING = 7
    PAYMENT_ORDER_STATUS_CREATE_FAILED = 8
    PAYMENT_ORDER_STATUS_REFUNDING = 9
    PAYMENT_ORDER_STATUS_REFUND_FAILED = 10


PaymentOrderStatusType = GenericEnumType(
    PaymentOrderStatus,
    storage_mode="value",
    read_modes=("value", "name"),
)

PaymentOrderStatusNameType = GenericEnumType(
    PaymentOrderStatus,
    storage_mode="name",
    read_modes=("name", "value"),
)


class PaymentBillingInterval(_Enum):
    PAYMENT_BILLING_INTERVAL_UNSPECIFIED = 0
    PAYMENT_BILLING_INTERVAL_ONE_TIME = 1
    PAYMENT_BILLING_INTERVAL_MONTHLY = 2
    PAYMENT_BILLING_INTERVAL_QUARTERLY = 3
    PAYMENT_BILLING_INTERVAL_YEARLY = 4


PaymentBillingIntervalType = GenericEnumType(
    PaymentBillingInterval,
    storage_mode="value",
    read_modes=("value", "name"),
)

PaymentBillingIntervalNameType = GenericEnumType(
    PaymentBillingInterval,
    storage_mode="name",
    read_modes=("name", "value"),
)


class PaymentEventType(_Enum):
    PAYMENT_EVENT_TYPE_UNSPECIFIED = 0
    PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED = 1
    PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED = 2
    PAYMENT_EVENT_TYPE_PAYMENT_FAILED = 3
    PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED = 4
    PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED = 5
    PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED = 6
    PAYMENT_EVENT_TYPE_REFUND_CREATED = 7
    PAYMENT_EVENT_TYPE_CHARGE_DISPUTED = 8


PaymentEventTypeType = GenericEnumType(
    PaymentEventType,
    storage_mode="value",
    read_modes=("value", "name"),
)

PaymentEventTypeNameType = GenericEnumType(
    PaymentEventType,
    storage_mode="name",
    read_modes=("name", "value"),
)


class RefundRequestStatus(_Enum):
    REFUND_REQUEST_STATUS_UNSPECIFIED = 0
    REFUND_REQUEST_STATUS_PENDING_APPROVAL = 1
    REFUND_REQUEST_STATUS_APPROVED = 2
    REFUND_REQUEST_STATUS_REJECTED = 3
    REFUND_REQUEST_STATUS_CANCELED = 4
    REFUND_REQUEST_STATUS_PROCESSING = 5
    REFUND_REQUEST_STATUS_SUCCEEDED = 6
    REFUND_REQUEST_STATUS_FAILED = 7


RefundRequestStatusType = GenericEnumType(
    RefundRequestStatus,
    storage_mode="value",
    read_modes=("value", "name"),
)

RefundRequestStatusNameType = GenericEnumType(
    RefundRequestStatus,
    storage_mode="name",
    read_modes=("name", "value"),
)


class CheckoutLineItem(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    name: Optional[str] = _Field(default="")
    description: Optional[str] = _Field(default="")
    amount_minor: Optional[int] = _Field(default=0)
    quantity: Optional[int] = _Field(default=0)
    external_product_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CheckoutLineItem")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CheckoutLineItem":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreateCheckoutResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    order_id: Optional[str] = _Field(default="")
    provider_session_id: Optional[str] = _Field(default="")
    checkout_url: Optional[str] = _Field(default="")
    provider: Optional["PaymentProviderKind"] = _Field(default=PaymentProviderKind(0))

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreateCheckoutResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreateCheckoutResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetPaymentOrderRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    order_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetPaymentOrderRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetPaymentOrderRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PaymentOrderResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    provider: Optional["PaymentProviderKind"] = _Field(default=PaymentProviderKind(0))
    provider_session_id: Optional[str] = _Field(default="")
    status: Optional["PaymentOrderStatus"] = _Field(default=PaymentOrderStatus(0))
    currency: Optional[str] = _Field(default="")
    total_amount_minor: Optional[int] = _Field(default=0)
    billing_interval: Optional[str] = _Field(default="")
    metadata: Optional[Dict[str, Any]] = _Field(default=None)
    created_at: Optional[str] = _Field(default="")
    updated_at: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PaymentOrderResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PaymentOrderResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPaymentOrdersRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    status: Optional["PaymentOrderStatus"] = _Field(default=PaymentOrderStatus(0))
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPaymentOrdersRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPaymentOrdersRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RefundPaymentRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    order_id: Optional[str] = _Field(default="")
    amount_minor: Optional[int] = _Field(default=0)
    reason: Optional[str] = _Field(default="")
    idempotency_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RefundPaymentRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RefundPaymentRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RefundPaymentResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_id: Optional[str] = _Field(default="")
    provider_refund_id: Optional[str] = _Field(default="")
    amount_minor: Optional[int] = _Field(default=0)
    status: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RefundPaymentResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RefundPaymentResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class SubmitRefundRequestRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    order_id: Optional[str] = _Field(default="")
    amount_minor: Optional[int] = _Field(default=0)
    reason: Optional[str] = _Field(default="")
    request_channel: Optional[str] = _Field(default="")
    requested_by: Optional[str] = _Field(default="")
    requested_by_display_name: Optional[str] = _Field(default="")
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    idempotency_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.SubmitRefundRequestRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "SubmitRefundRequestRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class GetRefundRequestRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_request_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.GetRefundRequestRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "GetRefundRequestRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListRefundRequestsRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    order_id: Optional[str] = _Field(default="")
    status: Optional["RefundRequestStatus"] = _Field(default=RefundRequestStatus(0))
    page_size: Optional[int] = _Field(default=0)
    page_token: Optional[str] = _Field(default="")
    business_ids: Optional[List[str]] = _Field(default=[])
    subject_ids: Optional[List[str]] = _Field(default=[])
    order_ids: Optional[List[str]] = _Field(default=[])
    statuses: Optional[List["RefundRequestStatus"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListRefundRequestsRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListRefundRequestsRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RefundReviewLogRecord(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    refund_request_id: Optional[str] = _Field(default="")
    action: Optional[str] = _Field(default="")
    actor_id: Optional[str] = _Field(default="")
    actor_display_name: Optional[str] = _Field(default="")
    comment: Optional[str] = _Field(default="")
    from_status: Optional[str] = _Field(default="")
    to_status: Optional[str] = _Field(default="")
    metadata: Optional[Dict[str, Any]] = _Field(default=None)
    created_at: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RefundReviewLogRecord")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RefundReviewLogRecord":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListRefundReviewLogsRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_request_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListRefundReviewLogsRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListRefundReviewLogsRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RefundRequestRecord(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    id: Optional[str] = _Field(default="")
    order_id: Optional[str] = _Field(default="")
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    status: Optional["RefundRequestStatus"] = _Field(default=RefundRequestStatus(0))
    requested_amount_minor: Optional[int] = _Field(default=0)
    approved_amount_minor: Optional[int] = _Field(default=0)
    currency: Optional[str] = _Field(default="")
    reason: Optional[str] = _Field(default="")
    request_channel: Optional[str] = _Field(default="")
    requested_by: Optional[str] = _Field(default="")
    requested_by_display_name: Optional[str] = _Field(default="")
    reviewer_id: Optional[str] = _Field(default="")
    reviewer_display_name: Optional[str] = _Field(default="")
    review_comment: Optional[str] = _Field(default="")
    provider_refund_id: Optional[str] = _Field(default="")
    payment_refund_id: Optional[str] = _Field(default="")
    error_message: Optional[str] = _Field(default="")
    metadata: Optional[Dict[str, Any]] = _Field(default=None)
    created_at: Optional[str] = _Field(default="")
    updated_at: Optional[str] = _Field(default="")
    reviewed_at: Optional[str] = _Field(default="")
    processed_at: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RefundRequestRecord")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RefundRequestRecord":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CancelRefundRequestRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_request_id: Optional[str] = _Field(default="")
    canceled_by: Optional[str] = _Field(default="")
    cancel_comment: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CancelRefundRequestRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CancelRefundRequestRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ApproveRefundRequestRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_request_id: Optional[str] = _Field(default="")
    approved_amount_minor: Optional[int] = _Field(default=0)
    reviewer_id: Optional[str] = _Field(default="")
    reviewer_display_name: Optional[str] = _Field(default="")
    review_comment: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ApproveRefundRequestRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ApproveRefundRequestRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class RejectRefundRequestRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_request_id: Optional[str] = _Field(default="")
    reviewer_id: Optional[str] = _Field(default="")
    reviewer_display_name: Optional[str] = _Field(default="")
    review_comment: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.RejectRefundRequestRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "RejectRefundRequestRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PaymentWebhookRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    provider: Optional["PaymentProviderKind"] = _Field(default=PaymentProviderKind(0))
    raw_body: Optional[bytes] = _Field(default=b"")
    signature: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PaymentWebhookRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PaymentWebhookRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class PaymentWebhookResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    accepted: Optional[bool] = _Field(default=False)
    event_type: Optional[str] = _Field(default="")
    provider_event_id: Optional[str] = _Field(default="")
    order_id: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.PaymentWebhookResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "PaymentWebhookResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPaymentProvidersRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPaymentProvidersRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPaymentProvidersRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPaymentProvidersResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    providers: Optional[List[str]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPaymentProvidersResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPaymentProvidersResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class CreateCheckoutRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    business_id: Optional[str] = _Field(default="")
    subject_id: Optional[str] = _Field(default="")
    provider: Optional["PaymentProviderKind"] = _Field(default=PaymentProviderKind(0))
    customer_email: Optional[str] = _Field(default="")
    currency: Optional[str] = _Field(default="")
    line_items: Optional[List["CheckoutLineItem"]] = _Field(default=[])
    billing_interval: Optional["PaymentBillingInterval"] = _Field(
        default=PaymentBillingInterval(0)
    )
    success_url: Optional[str] = _Field(default="")
    cancel_url: Optional[str] = _Field(default="")
    plan_id: Optional[str] = _Field(default="")
    metadata: Optional[Dict[str, str]] = _Field(default=None)
    idempotency_key: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.CreateCheckoutRequest")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "CreateCheckoutRequest":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListPaymentOrdersResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    orders: Optional[List["PaymentOrderResponse"]] = _Field(default=[])
    next_page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListPaymentOrdersResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListPaymentOrdersResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListRefundReviewLogsResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    review_logs: Optional[List["RefundReviewLogRecord"]] = _Field(default=[])

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListRefundReviewLogsResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListRefundReviewLogsResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


class ListRefundRequestsResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    refund_requests: Optional[List["RefundRequestRecord"]] = _Field(default=[])
    next_page_token: Optional[str] = _Field(default="")

    def to_protobuf(self) -> _message.Message:
        """Convert Pydantic model to protobuf message"""
        _proto = pool.FindMessageTypeByName("stew.api.v1.ListRefundRequestsResponse")
        _cls: Type[_message.Message] = message_factory.GetMessageClass(_proto)
        return model2protobuf(self, _cls())

    @classmethod
    def from_protobuf(cls, src: _message.Message) -> "ListRefundRequestsResponse":
        """Convert protobuf message to Pydantic model"""
        return protobuf2model(cls, src)


CheckoutLineItem.model_rebuild()
CreateCheckoutResponse.model_rebuild()
GetPaymentOrderRequest.model_rebuild()
PaymentOrderResponse.model_rebuild()
ListPaymentOrdersRequest.model_rebuild()
RefundPaymentRequest.model_rebuild()
RefundPaymentResponse.model_rebuild()
SubmitRefundRequestRequest.model_rebuild()
GetRefundRequestRequest.model_rebuild()
ListRefundRequestsRequest.model_rebuild()
RefundReviewLogRecord.model_rebuild()
ListRefundReviewLogsRequest.model_rebuild()
RefundRequestRecord.model_rebuild()
CancelRefundRequestRequest.model_rebuild()
ApproveRefundRequestRequest.model_rebuild()
RejectRefundRequestRequest.model_rebuild()
PaymentWebhookRequest.model_rebuild()
PaymentWebhookResponse.model_rebuild()
ListPaymentProvidersRequest.model_rebuild()
ListPaymentProvidersResponse.model_rebuild()
CreateCheckoutRequest.model_rebuild()
ListPaymentOrdersResponse.model_rebuild()
ListRefundReviewLogsResponse.model_rebuild()
ListRefundRequestsResponse.model_rebuild()
