# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import business_asset_browser_pb2 as business__asset__browser__pb2
from . import pricing_admin_pb2 as pricing__admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pricing_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PricingAdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPricingPagePreview = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/GetPricingPagePreview',
                request_serializer=pricing__admin__pb2.GetPricingPagePreviewRequest.SerializeToString,
                response_deserializer=pricing__admin__pb2.PricingPagePreviewResponse.FromString,
                _registered_method=True)
        self.EnsurePricingCollection = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/EnsurePricingCollection',
                request_serializer=pricing__admin__pb2.EnsurePricingCollectionRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.AssetCollection.FromString,
                _registered_method=True)
        self.ListPricingVersions = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/ListPricingVersions',
                request_serializer=pricing__admin__pb2.ListPricingVersionsRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.ListAssetVersionsResponse.FromString,
                _registered_method=True)
        self.CreatePricingDraft = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/CreatePricingDraft',
                request_serializer=pricing__admin__pb2.CreatePricingDraftRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.CreateDraftVersionResponse.FromString,
                _registered_method=True)
        self.GetPricingDraftContent = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/GetPricingDraftContent',
                request_serializer=pricing__admin__pb2.GetPricingDraftContentRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.GetAssetEntryTextResponse.FromString,
                _registered_method=True)
        self.SavePricingDraft = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/SavePricingDraft',
                request_serializer=pricing__admin__pb2.SavePricingDraftRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.UpdateDraftTextEntryResponse.FromString,
                _registered_method=True)
        self.PublishPricingDraft = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/PublishPricingDraft',
                request_serializer=pricing__admin__pb2.PublishPricingDraftRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.PublishDraftVersionResponse.FromString,
                _registered_method=True)
        self.ActivatePricingVersion = channel.unary_unary(
                '/stew.api.v1.PricingAdminService/ActivatePricingVersion',
                request_serializer=pricing__admin__pb2.ActivatePricingVersionRequest.SerializeToString,
                response_deserializer=business__asset__browser__pb2.ActivateAssetVersionResponse.FromString,
                _registered_method=True)


class PricingAdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPricingPagePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsurePricingCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPricingVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePricingDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPricingDraftContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePricingDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishPricingDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivatePricingVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPricingPagePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPricingPagePreview,
                    request_deserializer=pricing__admin__pb2.GetPricingPagePreviewRequest.FromString,
                    response_serializer=pricing__admin__pb2.PricingPagePreviewResponse.SerializeToString,
            ),
            'EnsurePricingCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsurePricingCollection,
                    request_deserializer=pricing__admin__pb2.EnsurePricingCollectionRequest.FromString,
                    response_serializer=business__asset__browser__pb2.AssetCollection.SerializeToString,
            ),
            'ListPricingVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPricingVersions,
                    request_deserializer=pricing__admin__pb2.ListPricingVersionsRequest.FromString,
                    response_serializer=business__asset__browser__pb2.ListAssetVersionsResponse.SerializeToString,
            ),
            'CreatePricingDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePricingDraft,
                    request_deserializer=pricing__admin__pb2.CreatePricingDraftRequest.FromString,
                    response_serializer=business__asset__browser__pb2.CreateDraftVersionResponse.SerializeToString,
            ),
            'GetPricingDraftContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPricingDraftContent,
                    request_deserializer=pricing__admin__pb2.GetPricingDraftContentRequest.FromString,
                    response_serializer=business__asset__browser__pb2.GetAssetEntryTextResponse.SerializeToString,
            ),
            'SavePricingDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePricingDraft,
                    request_deserializer=pricing__admin__pb2.SavePricingDraftRequest.FromString,
                    response_serializer=business__asset__browser__pb2.UpdateDraftTextEntryResponse.SerializeToString,
            ),
            'PublishPricingDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishPricingDraft,
                    request_deserializer=pricing__admin__pb2.PublishPricingDraftRequest.FromString,
                    response_serializer=business__asset__browser__pb2.PublishDraftVersionResponse.SerializeToString,
            ),
            'ActivatePricingVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivatePricingVersion,
                    request_deserializer=pricing__admin__pb2.ActivatePricingVersionRequest.FromString,
                    response_serializer=business__asset__browser__pb2.ActivateAssetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stew.api.v1.PricingAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stew.api.v1.PricingAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PricingAdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPricingPagePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/GetPricingPagePreview',
            pricing__admin__pb2.GetPricingPagePreviewRequest.SerializeToString,
            pricing__admin__pb2.PricingPagePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsurePricingCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/EnsurePricingCollection',
            pricing__admin__pb2.EnsurePricingCollectionRequest.SerializeToString,
            business__asset__browser__pb2.AssetCollection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPricingVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/ListPricingVersions',
            pricing__admin__pb2.ListPricingVersionsRequest.SerializeToString,
            business__asset__browser__pb2.ListAssetVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePricingDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/CreatePricingDraft',
            pricing__admin__pb2.CreatePricingDraftRequest.SerializeToString,
            business__asset__browser__pb2.CreateDraftVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPricingDraftContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/GetPricingDraftContent',
            pricing__admin__pb2.GetPricingDraftContentRequest.SerializeToString,
            business__asset__browser__pb2.GetAssetEntryTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePricingDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/SavePricingDraft',
            pricing__admin__pb2.SavePricingDraftRequest.SerializeToString,
            business__asset__browser__pb2.UpdateDraftTextEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishPricingDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/PublishPricingDraft',
            pricing__admin__pb2.PublishPricingDraftRequest.SerializeToString,
            business__asset__browser__pb2.PublishDraftVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivatePricingVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.PricingAdminService/ActivatePricingVersion',
            pricing__admin__pb2.ActivatePricingVersionRequest.SerializeToString,
            business__asset__browser__pb2.ActivateAssetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
