# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_discovery_pb2 as service__discovery__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceDiscoveryServiceStub(object):
    """==================== 服务定义 ====================

    服务注册和发现服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterService = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/RegisterService',
                request_serializer=service__discovery__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.DeregisterService = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/DeregisterService',
                request_serializer=service__discovery__pb2.DeregisterServiceRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.DeregisterServiceResponse.FromString,
                _registered_method=True)
        self.GetServiceInstances = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/GetServiceInstances',
                request_serializer=service__discovery__pb2.GetServiceInstancesRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.GetServiceInstancesResponse.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/ListServices',
                request_serializer=service__discovery__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.UpdateServiceHealth = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/UpdateServiceHealth',
                request_serializer=service__discovery__pb2.UpdateServiceHealthRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.UpdateServiceHealthResponse.FromString,
                _registered_method=True)
        self.ServiceHealthCheck = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/ServiceHealthCheck',
                request_serializer=service__discovery__pb2.ServiceHealthCheckRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.ServiceHealthCheckResponse.FromString,
                _registered_method=True)
        self.UploadServiceConfig = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/UploadServiceConfig',
                request_serializer=service__discovery__pb2.UploadServiceConfigRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.UploadServiceConfigResponse.FromString,
                _registered_method=True)
        self.GetServiceConfig = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/GetServiceConfig',
                request_serializer=service__discovery__pb2.GetServiceConfigRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.GetServiceConfigResponse.FromString,
                _registered_method=True)
        self.UploadProtobufDescriptor = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/UploadProtobufDescriptor',
                request_serializer=service__discovery__pb2.UploadProtobufDescriptorRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.UploadProtobufDescriptorResponse.FromString,
                _registered_method=True)
        self.GetProtobufDescriptor = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/GetProtobufDescriptor',
                request_serializer=service__discovery__pb2.GetProtobufDescriptorRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.GetProtobufDescriptorResponse.FromString,
                _registered_method=True)
        self.ListProtobufDescriptors = channel.unary_unary(
                '/stew.api.v1.ServiceDiscoveryService/ListProtobufDescriptors',
                request_serializer=service__discovery__pb2.ListProtobufDescriptorsRequest.SerializeToString,
                response_deserializer=service__discovery__pb2.ListProtobufDescriptorsResponse.FromString,
                _registered_method=True)


class ServiceDiscoveryServiceServicer(object):
    """==================== 服务定义 ====================

    服务注册和发现服务
    """

    def RegisterService(self, request, context):
        """注册服务实例
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterService(self, request, context):
        """注销服务实例
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInstances(self, request, context):
        """获取服务实例列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """列出所有服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceHealth(self, request, context):
        """更新服务健康状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServiceHealthCheck(self, request, context):
        """服务健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadServiceConfig(self, request, context):
        """上传服务配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceConfig(self, request, context):
        """获取服务配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadProtobufDescriptor(self, request, context):
        """上传 protobuf 描述符
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProtobufDescriptor(self, request, context):
        """获取 protobuf 描述符
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProtobufDescriptors(self, request, context):
        """列出可用的 protobuf 描述符
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=service__discovery__pb2.RegisterServiceRequest.FromString,
                    response_serializer=service__discovery__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'DeregisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterService,
                    request_deserializer=service__discovery__pb2.DeregisterServiceRequest.FromString,
                    response_serializer=service__discovery__pb2.DeregisterServiceResponse.SerializeToString,
            ),
            'GetServiceInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInstances,
                    request_deserializer=service__discovery__pb2.GetServiceInstancesRequest.FromString,
                    response_serializer=service__discovery__pb2.GetServiceInstancesResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=service__discovery__pb2.ListServicesRequest.FromString,
                    response_serializer=service__discovery__pb2.ListServicesResponse.SerializeToString,
            ),
            'UpdateServiceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceHealth,
                    request_deserializer=service__discovery__pb2.UpdateServiceHealthRequest.FromString,
                    response_serializer=service__discovery__pb2.UpdateServiceHealthResponse.SerializeToString,
            ),
            'ServiceHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ServiceHealthCheck,
                    request_deserializer=service__discovery__pb2.ServiceHealthCheckRequest.FromString,
                    response_serializer=service__discovery__pb2.ServiceHealthCheckResponse.SerializeToString,
            ),
            'UploadServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadServiceConfig,
                    request_deserializer=service__discovery__pb2.UploadServiceConfigRequest.FromString,
                    response_serializer=service__discovery__pb2.UploadServiceConfigResponse.SerializeToString,
            ),
            'GetServiceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceConfig,
                    request_deserializer=service__discovery__pb2.GetServiceConfigRequest.FromString,
                    response_serializer=service__discovery__pb2.GetServiceConfigResponse.SerializeToString,
            ),
            'UploadProtobufDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadProtobufDescriptor,
                    request_deserializer=service__discovery__pb2.UploadProtobufDescriptorRequest.FromString,
                    response_serializer=service__discovery__pb2.UploadProtobufDescriptorResponse.SerializeToString,
            ),
            'GetProtobufDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProtobufDescriptor,
                    request_deserializer=service__discovery__pb2.GetProtobufDescriptorRequest.FromString,
                    response_serializer=service__discovery__pb2.GetProtobufDescriptorResponse.SerializeToString,
            ),
            'ListProtobufDescriptors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProtobufDescriptors,
                    request_deserializer=service__discovery__pb2.ListProtobufDescriptorsRequest.FromString,
                    response_serializer=service__discovery__pb2.ListProtobufDescriptorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stew.api.v1.ServiceDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stew.api.v1.ServiceDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceDiscoveryService(object):
    """==================== 服务定义 ====================

    服务注册和发现服务
    """

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/RegisterService',
            service__discovery__pb2.RegisterServiceRequest.SerializeToString,
            service__discovery__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/DeregisterService',
            service__discovery__pb2.DeregisterServiceRequest.SerializeToString,
            service__discovery__pb2.DeregisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/GetServiceInstances',
            service__discovery__pb2.GetServiceInstancesRequest.SerializeToString,
            service__discovery__pb2.GetServiceInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/ListServices',
            service__discovery__pb2.ListServicesRequest.SerializeToString,
            service__discovery__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServiceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/UpdateServiceHealth',
            service__discovery__pb2.UpdateServiceHealthRequest.SerializeToString,
            service__discovery__pb2.UpdateServiceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServiceHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/ServiceHealthCheck',
            service__discovery__pb2.ServiceHealthCheckRequest.SerializeToString,
            service__discovery__pb2.ServiceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/UploadServiceConfig',
            service__discovery__pb2.UploadServiceConfigRequest.SerializeToString,
            service__discovery__pb2.UploadServiceConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/GetServiceConfig',
            service__discovery__pb2.GetServiceConfigRequest.SerializeToString,
            service__discovery__pb2.GetServiceConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadProtobufDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/UploadProtobufDescriptor',
            service__discovery__pb2.UploadProtobufDescriptorRequest.SerializeToString,
            service__discovery__pb2.UploadProtobufDescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProtobufDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/GetProtobufDescriptor',
            service__discovery__pb2.GetProtobufDescriptorRequest.SerializeToString,
            service__discovery__pb2.GetProtobufDescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProtobufDescriptors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stew.api.v1.ServiceDiscoveryService/ListProtobufDescriptors',
            service__discovery__pb2.ListProtobufDescriptorsRequest.SerializeToString,
            service__discovery__pb2.ListProtobufDescriptorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
